---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: bamboo-connector
  namespace: connectors
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:git-*
spec:
  releaseName: bamboo-connector
  chart:
    git: git@github.com:jakeva/helm-operator-get-started
    path: charts/bamboo-connector
    ref: master
  values:
    image:
      repository: "673102273038.dkr.ecr.us-west-2.amazonaws.com/bamboo_connector"
      tag: "git-6dc31ec4d60acf7add57705f69843d8ec43166c7"
    replicaCount: 1
    hpa:
      enabled: false
